### ISSUE TITLE
Valid syntax for options.

### ISSUE THREAD

**Issue by ygcodes90025** [blakedhamilton/Coinbase-Pro#2]
Hello and thank you for the library, 
I'm sorry in advance If i'm not correctly using this tab as this maynot be an issue with the code but rather my lack of knowledge. 
What syntax should be passed to the "Options" parameter, for example: $coinbase->orders->place($options = []); 
I have tried passing it an array, json object, or just a string, however I receive an error, Uncaught Error: Call to undefined method Coinbase\Endpoints\Orders::place().. 
I'm using the sandbox env. Could you please provide me with a valid example that I could pass in? 
Thank you

**Comment by blakedhamilton** [comment]
Hi @ygcodes90025, I've just taken a look at the issue. It appears that the function name wasn't updated in the documentation by mistake.

The function is actually called "create" so $coinbase->orders->create($options) will work for you and it takes an array as a parameter! 

Additionally I've just seen that Coinbase has updated their API endpoints which are now hosted underneath a different subdomain. I'm unsure if they're still supporting the old subdomain which the library is sending requests to at the moment, so requests may fail for that reason unfortunately.

 I will get the documentation and endpoints updated ASAP, sorry for the inconvenience!

**Comment by ygcodes90025** [comment]
got it thank you very much, I was able to submit a test order now. :-) 

Yes, I've noticed they have updated their endpoints, in the meantime, the old ones still seem to work for the methods I've tried so far.
